/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as RegionsRouteImport } from './pages/regions'
import { Route as CountriesRouteRouteImport } from './pages/countries.route'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ItemsIndexRouteImport } from './pages/items.index'
import { Route as ItemMarketIndexRouteImport } from './pages/itemMarket.index'
import { Route as DepositsIndexRouteImport } from './pages/deposits.index'
import { Route as CountriesIndexRouteImport } from './pages/countries.index'
import { Route as ItemDepositsItemCodeRouteImport } from './pages/itemDeposits.$itemCode'
import { Route as CountriesMatchupRouteImport } from './pages/countries.matchup'
import { Route as CountriesAlliancesRouteImport } from './pages/countries.alliances'
import { Route as CountriesCountryIdRouteImport } from './pages/countries.$countryId'

const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRouteRoute = CountriesRouteRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemMarketIndexRoute = ItemMarketIndexRouteImport.update({
  id: '/itemMarket/',
  path: '/itemMarket/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsIndexRoute = DepositsIndexRouteImport.update({
  id: '/deposits/',
  path: '/deposits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountriesRouteRoute,
} as any)
const ItemDepositsItemCodeRoute = ItemDepositsItemCodeRouteImport.update({
  id: '/itemDeposits/$itemCode',
  path: '/itemDeposits/$itemCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesMatchupRoute = CountriesMatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => CountriesRouteRoute,
} as any)
const CountriesAlliancesRoute = CountriesAlliancesRouteImport.update({
  id: '/alliances',
  path: '/alliances',
  getParentRoute: () => CountriesRouteRoute,
} as any)
const CountriesCountryIdRoute = CountriesCountryIdRouteImport.update({
  id: '/$countryId',
  path: '/$countryId',
  getParentRoute: () => CountriesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countries': typeof CountriesRouteRouteWithChildren
  '/regions': typeof RegionsRoute
  '/countries/$countryId': typeof CountriesCountryIdRoute
  '/countries/alliances': typeof CountriesAlliancesRoute
  '/countries/matchup': typeof CountriesMatchupRoute
  '/itemDeposits/$itemCode': typeof ItemDepositsItemCodeRoute
  '/countries/': typeof CountriesIndexRoute
  '/deposits': typeof DepositsIndexRoute
  '/itemMarket': typeof ItemMarketIndexRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/regions': typeof RegionsRoute
  '/countries/$countryId': typeof CountriesCountryIdRoute
  '/countries/alliances': typeof CountriesAlliancesRoute
  '/countries/matchup': typeof CountriesMatchupRoute
  '/itemDeposits/$itemCode': typeof ItemDepositsItemCodeRoute
  '/countries': typeof CountriesIndexRoute
  '/deposits': typeof DepositsIndexRoute
  '/itemMarket': typeof ItemMarketIndexRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countries': typeof CountriesRouteRouteWithChildren
  '/regions': typeof RegionsRoute
  '/countries/$countryId': typeof CountriesCountryIdRoute
  '/countries/alliances': typeof CountriesAlliancesRoute
  '/countries/matchup': typeof CountriesMatchupRoute
  '/itemDeposits/$itemCode': typeof ItemDepositsItemCodeRoute
  '/countries/': typeof CountriesIndexRoute
  '/deposits/': typeof DepositsIndexRoute
  '/itemMarket/': typeof ItemMarketIndexRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/countries'
    | '/regions'
    | '/countries/$countryId'
    | '/countries/alliances'
    | '/countries/matchup'
    | '/itemDeposits/$itemCode'
    | '/countries/'
    | '/deposits'
    | '/itemMarket'
    | '/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/regions'
    | '/countries/$countryId'
    | '/countries/alliances'
    | '/countries/matchup'
    | '/itemDeposits/$itemCode'
    | '/countries'
    | '/deposits'
    | '/itemMarket'
    | '/items'
  id:
    | '__root__'
    | '/'
    | '/countries'
    | '/regions'
    | '/countries/$countryId'
    | '/countries/alliances'
    | '/countries/matchup'
    | '/itemDeposits/$itemCode'
    | '/countries/'
    | '/deposits/'
    | '/itemMarket/'
    | '/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountriesRouteRoute: typeof CountriesRouteRouteWithChildren
  RegionsRoute: typeof RegionsRoute
  ItemDepositsItemCodeRoute: typeof ItemDepositsItemCodeRoute
  DepositsIndexRoute: typeof DepositsIndexRoute
  ItemMarketIndexRoute: typeof ItemMarketIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itemMarket/': {
      id: '/itemMarket/'
      path: '/itemMarket'
      fullPath: '/itemMarket'
      preLoaderRoute: typeof ItemMarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/': {
      id: '/deposits/'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof DepositsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof CountriesRouteRoute
    }
    '/itemDeposits/$itemCode': {
      id: '/itemDeposits/$itemCode'
      path: '/itemDeposits/$itemCode'
      fullPath: '/itemDeposits/$itemCode'
      preLoaderRoute: typeof ItemDepositsItemCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/matchup': {
      id: '/countries/matchup'
      path: '/matchup'
      fullPath: '/countries/matchup'
      preLoaderRoute: typeof CountriesMatchupRouteImport
      parentRoute: typeof CountriesRouteRoute
    }
    '/countries/alliances': {
      id: '/countries/alliances'
      path: '/alliances'
      fullPath: '/countries/alliances'
      preLoaderRoute: typeof CountriesAlliancesRouteImport
      parentRoute: typeof CountriesRouteRoute
    }
    '/countries/$countryId': {
      id: '/countries/$countryId'
      path: '/$countryId'
      fullPath: '/countries/$countryId'
      preLoaderRoute: typeof CountriesCountryIdRouteImport
      parentRoute: typeof CountriesRouteRoute
    }
  }
}

interface CountriesRouteRouteChildren {
  CountriesCountryIdRoute: typeof CountriesCountryIdRoute
  CountriesAlliancesRoute: typeof CountriesAlliancesRoute
  CountriesMatchupRoute: typeof CountriesMatchupRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
}

const CountriesRouteRouteChildren: CountriesRouteRouteChildren = {
  CountriesCountryIdRoute: CountriesCountryIdRoute,
  CountriesAlliancesRoute: CountriesAlliancesRoute,
  CountriesMatchupRoute: CountriesMatchupRoute,
  CountriesIndexRoute: CountriesIndexRoute,
}

const CountriesRouteRouteWithChildren = CountriesRouteRoute._addFileChildren(
  CountriesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountriesRouteRoute: CountriesRouteRouteWithChildren,
  RegionsRoute: RegionsRoute,
  ItemDepositsItemCodeRoute: ItemDepositsItemCodeRoute,
  DepositsIndexRoute: DepositsIndexRoute,
  ItemMarketIndexRoute: ItemMarketIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
