/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as RegionsRouteImport } from './pages/regions'
import { Route as CountriesRouteImport } from './pages/countries'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ItemsIndexRouteImport } from './pages/items.index'
import { Route as DepositsIndexRouteImport } from './pages/deposits.index'
import { Route as ItemDepositsItemCodeRouteImport } from './pages/itemDeposits.$itemCode'

const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsIndexRoute = DepositsIndexRouteImport.update({
  id: '/deposits/',
  path: '/deposits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemDepositsItemCodeRoute = ItemDepositsItemCodeRouteImport.update({
  id: '/itemDeposits/$itemCode',
  path: '/itemDeposits/$itemCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countries': typeof CountriesRoute
  '/regions': typeof RegionsRoute
  '/itemDeposits/$itemCode': typeof ItemDepositsItemCodeRoute
  '/deposits': typeof DepositsIndexRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countries': typeof CountriesRoute
  '/regions': typeof RegionsRoute
  '/itemDeposits/$itemCode': typeof ItemDepositsItemCodeRoute
  '/deposits': typeof DepositsIndexRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countries': typeof CountriesRoute
  '/regions': typeof RegionsRoute
  '/itemDeposits/$itemCode': typeof ItemDepositsItemCodeRoute
  '/deposits/': typeof DepositsIndexRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/countries'
    | '/regions'
    | '/itemDeposits/$itemCode'
    | '/deposits'
    | '/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/countries'
    | '/regions'
    | '/itemDeposits/$itemCode'
    | '/deposits'
    | '/items'
  id:
    | '__root__'
    | '/'
    | '/countries'
    | '/regions'
    | '/itemDeposits/$itemCode'
    | '/deposits/'
    | '/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountriesRoute: typeof CountriesRoute
  RegionsRoute: typeof RegionsRoute
  ItemDepositsItemCodeRoute: typeof ItemDepositsItemCodeRoute
  DepositsIndexRoute: typeof DepositsIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/': {
      id: '/deposits/'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof DepositsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itemDeposits/$itemCode': {
      id: '/itemDeposits/$itemCode'
      path: '/itemDeposits/$itemCode'
      fullPath: '/itemDeposits/$itemCode'
      preLoaderRoute: typeof ItemDepositsItemCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountriesRoute: CountriesRoute,
  RegionsRoute: RegionsRoute,
  ItemDepositsItemCodeRoute: ItemDepositsItemCodeRoute,
  DepositsIndexRoute: DepositsIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
